CXX=g++ -g -std=c++11

all: maptest0 maptest1 maptest2 maptest3 maptest4 maptest5 maptest6 maptest7 maptest8

maptest0: maptest0.cpp unorderedmap.h unorderedmap.cpp
	$(CXX)  maptest0.cpp -o maptest0
	
maptest1: maptest1.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest1.cpp -o maptest1
	
maptest2: maptest2.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest2.cpp -o maptest2
	
maptest3: maptest3.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest3.cpp -o maptest3
	
maptest4: maptest4.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest4.cpp -o maptest4
	
maptest5: maptest5.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest5.cpp -o maptest5
	
maptest6: maptest6.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest6.cpp -o maptest6
	
maptest7: maptest7.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest7.cpp -o maptest7

maptest8: maptest8.cpp unorderedmap.h unorderedmap.cpp
	$(CXX) -g maptest8.cpp -o maptest8
	

	
clean:
	rm -f *.o maptest0 maptest1 maptest2 maptest3 maptest4 maptest5 maptest6 maptest7 maptest8
